# Hexo 配置文件
## 文档：https://hexo.io/zh-cn/docs/configuration.html
## 源码：https://github.com/hexojs/hexo/

# 网站信息
title: 渝伴的小窝 # 网站标题
subtitle: "寻找属于自己的宁静角落"
description: "渝伴的小窝，一个心灵的栖息地。在这里，我将分享对技术的探索，对生活的思考，以及在日常中追寻内心深处的真实与自由。"
keywords:
  - "博客"
  - "技术"
  - "生活"
  - "心灵成长"
  - "思考"
  - "自我探索"
  - "编程"
  - "哲学"
  - "个人成长"
  - "自由"
author: Yuban # 作者名
language: zh-CN # 网站语言，改成中文可设为 zh-CN
timezone: Asia/Shanghai # 网站时区，推荐设为 Asia/Shanghai

# 网址设置
## 如果你使用 GitHub Pages，url 设置为 'https://username.github.io/项目名'
url: https://blog.osyb.cn

# 最佳永久链接格式 (同时需安装 hexo-abbrlink 插件)
permalink: posts/:title/ # 使用文章唯一ID作为标识

# 默认值配置
permalink_defaults:
  lang: zh-CN # 默认语言标识
  categories: tech # 默认分类

# URL美化设置 (推荐生产环境配置)
pretty_urls:
  trailing_index: false # 始终去除index.html
  trailing_html: false # 去除.html后缀

# 目录结构
source_dir: source # 源文件目录
public_dir: public # 生成的静态文件目录
tag_dir: tags # 标签目录
archive_dir: archives # 归档目录
category_dir: categories # 分类目录
code_dir: downloads/code # 代码下载目录
i18n_dir: :lang # 多语言目录结构
skip_render: # 跳过渲染的文件（支持 glob 表达式）

# 写作设置
new_post_name: :title.md # 新文章的文件名
default_layout: post # 默认布局
titlecase: false # 是否将标题转换为标题格式
external_link:
  enable: true # 是否在新标签页中打开外部链接
  field: site # 应用于整站
  exclude: "" # 排除的链接（可填域名）
filename_case: 0 # 文件名大小写：0 保持原样，1 全小写，2 全大写
render_drafts: false # 是否渲染草稿
post_asset_folder: false # 是否为每篇文章创建资源文件夹
relative_link: false # 是否使用相对链接
future: true # 是否显示未来的文章
syntax_highlighter: highlight.js # 语法高亮工具（也可设为 prismjs）

# highlight.js 配置（当 syntax_highlighter 设置为 highlight.js 时）
highlight:
  line_number: true # 显示行号
  auto_detect: false # 自动检测语言
  tab_replace: "" # 替换 tab 字符
  wrap: true # 是否换行
  hljs: false # 启用 highlight.js 样式（适用于某些主题）

# PrismJS 配置（当 syntax_highlighter 设置为 prismjs 时）
prismjs:
  preprocess: true
  line_number: true
  tab_replace: ""

# 首页设置
index_generator:
  path: "" # 首页路径
  per_page: 10 # 每页显示的文章数
  order_by: -date # 文章排序方式（默认按日期倒序）

# 分类与标签
default_category: uncategorized # 默认分类
category_map: # 分类名称映射（可自定义）
tag_map: # 标签名称映射（可自定义）

# 元信息标签（HTML meta 标签）
meta_generator: true # 是否生成 Hexo 版本的 meta 标签

# 日期/时间格式（使用 Moment.js）
date_format: YYYY-MM-DD # 日期格式
time_format: HH:mm:ss # 时间格式
updated_option: "mtime" # 更新时间来源：mtime（文件修改时间）| date（文章日期）| empty（不显示）

# 分页配置
per_page: 10 # 每页文章数量（0 表示不分页）
pagination_dir: page # 分页目录名，如 page/2、page/3

# 包含 / 排除 文件（仅作用于 source/ 目录）
include:
exclude:
ignore:

# 扩展配置
## 插件：https://hexo.io/plugins/
## 主题：https://hexo.io/themes/
theme: anzhiyu # 使用的主题名称

# 部署配置
## 文档：https://hexo.io/docs/one-command-deployment
deploy:
  type: # 部署方式（如 git，可配合插件 hexo-deployer-git 使用）

sitemap:
  path: sitemap.xml

feed:
  type: atom # 可选：atom / rss2 / json
  path: atom.xml # 输出文件名，默认是 atom.xml
  limit: 20 # 输出文章数量
  hub:
  content: true # 是否包含全文

#envelope_comment
#seehttps://akilar.top/posts/e2d3c450/
envelope_comment:
  enable: true #控制开关
  custom_pic:
    cover: https://npm.elemecdn.com/hexo-butterfly-envelope/lib/violet.jpg #信笺头部图片
    line: https://npm.elemecdn.com/hexo-butterfly-envelope/lib/line.png #信笺底部图片
    beforeimg: https://npm.elemecdn.com/hexo-butterfly-envelope/lib/before.png # 信封前半部分
    afterimg: https://npm.elemecdn.com/hexo-butterfly-envelope/lib/after.png # 信封后半部分
  message: #信笺正文，多行文本，写法如下
    - 有什么想问的？
    - 有什么想说的？
    - 有什么想吐槽的？
    - 哪怕是有什么想吃的，都可以告诉我哦~
  bottom: 自动书记人偶竭诚为您服务！ #仅支持单行文本
  height: #1024px，信封划出的高度
  path: #【可选】comments 的路径名称。默认为 comments，生成的页面为 comments/index.html
  front_matter: #【可选】comments页面的 front_matter 配置
    title: 留言板
    comments: true
    top_img: false
    type: envelope
